#-*- coding:utf-8 -*-
#
plotting_config:
  kwargs_feed:
    color: "tab:blue"
    label: "feed"
  kwargs_pee_mica:
    color: "gold"
    label: "pee (mica)"
  kwargs_pee_no_mica:
    color: "red"
    label: "pee (no mica)"
  kwargs_pee_no_trocken_windel:
    color: "deepskyblue"
    label: "Windel (trocken)"
  kwargs_pee_trocken_windel:
    color: "magenta"
    label: "Windel (no trocken)"
  bedtime_colors: # also uses the same color for getuptime
    color: "green"
    label: "Wake up/Sleep time"
    linewidth: 3

numbers_config:
  bedtime: 21
  getuptime: 7

converting_dict_pee:
  'en la mica y pa침al mojado': "Windel: nass, Mica: True"
  "mica: true  windel: trocken": "Windel: trocken, Mica: True"
  "en la mica": "Mica: True, Windel: trocken"
  "pa침al mojado": "Windel: nass, Mica: False"
  "pa침al mojado y en la mica": "Windel: nass, Mica: True"
  "en el pa침al": "Windel: nass, Mica: False"
  "en el pa침al y en la mica": "Windel: nass, Mica: False"
  "en la mica": "Windel: trocken, Mica: True"
  "en la mica despu칠s de llegar": "Windel: trocken, Mica: True"
  "pipi in mica  windel trocken": "Windel: trocken, Mica: True"
  "in die mica": "Windel: trocken, Mica: True"
  "15 despu칠s de comer. se despert칩. cuerpo tenso. pipi": "Windel: nass, Mica: True"
  "in mica  windel trocken": "Windel: trocken, Mica: True"
  "pipi in mica. windel feucht": "Windel: feucht, Mica: True"
  "en el cambiador. ": "Windel: feucht, Mica: False"
  "in windel": "Windel: nass, Mica: True"
  "en la mica y pa침al mojado. despu칠s de despertarse": "Windel: nass, Mica: True"
  "pa침al": "Windel: nass, Mica: True"
  "mica! trocken!": "Windel: trocken, Mica: True"
  "en la mica. wurde unruhig beim wickeln": "Windel: nass, Mica: True"
  "pa침al lleno. despu칠s del ba침o en la toalla": "Windel: nass, Mica: True"
  "in die windel": "Windel: nass, Mica: True"
  "windel nass": "Windel: nass, Mica: True"
  "en el pa침al y un poquito en la mica": "Windel: nass, Mica: True"
  "mica y pa침al mojado": "Windel: nass, Mica: True"
  "en la mica y pa침al lleno": "Windel: nass, Mica: True"
  "windel leer  pipi ins t칬pfchen": "Windel: trocken, Mica: True"
  "en la mica un poquito y pa침al mojado": "Windel: feucht, Mica: True"
  "windel und t칬pfchen": "Windel: feucht, Mica: True"
  "mica  windel trocken": "Windel: trocken, Mica: True"
  "windel voll und in t칬pfchen": "Windel: nass, Mica: True"
  "en la mica!": "Windel: nass, Mica: True"
  "en la mica y pa침al": "Windel: nass, Mica: True"
  "en el cambiador y pa침al mojado": "Windel: nass, Mica: False"
  "en la mica  y el pa침al mojado. llor칩 antes de hacer pip칤": "Windel: nass, Mica: True"
  "pa침al lleno": "Windel: nass, Mica: False"
  "in die mica. windel nass": "Windel: nass, Mica: True"
  "in das t칬pfchen! windel feucht": "Windel: nass, Mica: True"
  "w칛hrend nackt zeit": "Windel: nass, Mica: False"
  "pa침al lleno y pip칤 en la mica": "Windel: nass, Mica: True"
  "mica und nass": "Windel: nass, Mica: True"
  "mica y pa침al lleno": "Windel: nass, Mica: True"
  "en la mica. wurde unruhig beim schlafen. ": "Windel: nass, Mica: True"
  "en la mica. apenas se despert칩. pa침al mojado": "Windel: nass, Mica: True"
  "en el cambiador": "Windel: nass, Mica: False"
  "mica und windel nass": "Windel: nass, Mica: True"
  "en la mica y el pa침al lleno": "Windel: nass, Mica: True"
  "mica!": "Windel: trocken, Mica: True"
  "kurz geweint. pip칤 in potty": "Windel: trocken, Mica: True"
  "en la mica. se quej칩 antes de hacer": "Windel: trocken, Mica: True"
  "en la mica despu칠s de despertarse": "Windel: trocken, Mica: True"
  "pipi ins t칬pfchen. windel feucht.": "Windel: feucht, Mica: True"
  "en la mica y pa침al estaba lleno": "Windel: nass, Mica: True"
  "pipi in t칬pfchen  windel trocken": "Windel: trocken, Mica: True"
  "t칬pfchen und windel": "Windel: nass, Mica: True"
  "en la mica ": "Windel: trocken, Mica: True"
  "en el pa침al y mica": "Windel: nass, Mica: True"
  "en la mica. se puso inc칩moda pero no llor칩. el pa침al estaba seco": "Windel: feucht, Mica: True"
  "windel voll": "Windel: nass, Mica: True"
  "en la mica y en el pa침al": "Windel: nass, Mica: True"
  "t칬pfchen und windeln": "Windel: nass, Mica: True"
  "en la mica!! ": "Windel: nass, Mica: True"
  "en el cambiador. llor칩": "Windel: nass, Mica: False"
  "pipi in mica. windel nass": "Windel: nass, Mica: True"
  "mica: true  windel: nass": "Windel: nass, Mica: True"
  "mica: true": "Windel: trocken, Mica: True"
  "pa침al  mojado": "Windel: nass, Mica: False"
  "windel nass + pipi en la mica": "Windel: nass, Mica: True"
  "pipi un mica  windel trocken": "Windel: trocken, Mica: True"
  "en en pa침al": "Windel: nass, Mica: False"
  "windel nass. pipi ins t칬pfchen.": "Windel: nass, Mica: True"
  "en la mica y pa침al mojado ": "Windel: nass, Mica: True"
  "in die windel. hatte es durch weinen angek칲ndigt. tim war zu sp칛t.": "Windel: nass, Mica: False"
  "wenig in der windel": "Windel: feucht, Mica: False"
  "windel trocken! in mica!": "Windel: trocken, Mica: True"
  "in mica. windel trocken": "Windel: trocken, Mica: True"
  "en la mica. se quej칩 despu칠s de despertarse": "Windel: trocken, Mica: True"
  "en la mica. arque칩 la espalda mientras en el cambiador": "Windel: trocken, Mica: True"
  "en la mica despu칠s de llegar y pa침al mojado": "Windel: nass, Mica: True"
  "windel voll. ": "Windel: nass, Mica: False"
  "mica!!": "Windel: trocken, Mica: True"
  "en la mica. 15 minutos despu칠s de comer": "Windel: trocken, Mica: True"
  "w칛hrend trinken aufgeh칬rt und dann angefangen zu pinkeln.": "Windel: trocken, Mica: True"
  "mica: false  windel: nass": "Windel: nass, Mica: False"
  "pipi t칬pfchen": "Windel: nass, Mica: True"
  "mica": "Windel: nass, Mica: True"
  "t칬pfchen + windel (gut voll)": "Windel: nass, Mica: True"
  "pipi in mica  windel voll": "Windel: nass, Mica: True"
  "pipi en la mica": "Windel: nass, Mica: True"


converting_dict_poo:
  "En el pa침al": "Windel: voll, Mica: False"
  "En la mica": "Windel: leer, Mica: True"
  "En la mica y pa침al mojado": "Windel: leer, Mica: True"
  "In die Windel": "Windel: voll, Mica: False"
  "Popo in T칬pfchen  Pipi zum Teil": "Windel: leer, Mica: True"
  "Beides in mica!": "Windel: leer, Mica: True"
  "Un poquito en el pa침al y despu칠s en la mica. La vi hacer fuerza": "Windel: bisschen, Mica: True"
  "Windel voll mit Popo": "Windel: voll, Mica: True"
  "En la taza!!!! ": "Windel: leer, Mica: True"
  "Una gota en la mica": "Windel: leer, Mica: True"
  "Pa침al mojado y pip칤 y pop칩 en m la mica": "Windel: leer, Mica: True"
  "W칛hrend dem stillen": "Windel: leer, Mica: True"
  "En la Mica": "Windel: leer, Mica: True"
  "Pipi ins T칬pfchen  Pop Windel": "Windel: voll, Mica: False"
  "Pipi en el pa침al y pop칩 en la mica": "Windel: leer, Mica: True"
  "En la mica. Pa침al lleno": "Windel: voll, Mica: False"
  "En la mica. Pa침al estaba mojado": "Windel: leer, Mica: True"
  "Pipi und popo in die Windel und nach dem Essen": "Windel: voll, Mica: False"
  "En la mica  despu칠s de comer y antes de salir de la casa": "Windel: leer, Mica: True"
  "En la mica. Par칩 de tomar": "Windel: leer, Mica: True"
  "En la mica. Se puso intranquila mientras dorm칤a": "Windel: leer, Mica: True"
  "En la mica. Empez칩 en el pa침al": "Windel: bisschen, Mica: True"
  "En la mica. Despu칠s de despertarse  15 minutos despu칠s de comer. Arque칩 la espalda antes de hacer pip칤": "Windel: leer, Mica: True"
  "Mica": "Windel: leer, Mica: True"
  "Windel und mica": "Windel: bisschen, Mica: True"
  "Windel voll. Pipi in T칬pfchen": "Windel: voll, Mica: False"
  "Popo en la mica. Se despert칩 y llor칩. Pipi en el pa침al": "Windel: leer, Mica: True"
  "En la mica. Kein Signal. Nach dem wach werden": "Windel: leer, Mica: True"
  "En la mica mientras com칤a. Se침al se puso inc칩moda": "Windel: leer, Mica: True"
  "En la mica despues de despertarse": "Windel: leer, Mica: True"
  "En el pa침al. Llor칩 cuando se hizo": "Windel: leer, Mica: True"
  "I'm T칬pfchen! Nach IKEA!": "Windel: leer, Mica: True"
  "En la mica. Wurde wach und unruhig": "Windel: leer, Mica: True"
  "Pa침al": "Windel: voll, Mica: False"
  "Empez칩 en el pa침al  despu칠s en la mica": "Windel: bisschen, Mica: True"
  "In die Windel. War unruhig. Danach pipi und noch ein bisschen popo in die Mica": "Windel: bisschen, Mica: True"
  "En la mica pip칤 y popo. El pa침al estaba mojado": "Windel: leer, Mica: True"
  "Popo in die Windel Pipi ins T칬pfchen": "Windel: voll, Mica: False"
  "In die Windel  auf T칬pfchen nochmal Pipi und Popo. Keine Anzeichen. Im Schlaf.": "Windel: voll, Mica: False"
  "Fuera del pa침al 游땯": "Windel: voll, Mica: False"
  "Popo en la mica": "Windel: leer, Mica: True"
  "popo in t칬pfchen  pipi zum teil": "Windel: leer, Mica: True"
